"""
report_generator.py — EcoWatch AI (fpdf2 >= 2.7 compatible)
Generates a formal PDF compliance report from inference results.
Uses fpdf2's built-in Unicode support — no external font files required.
"""

import os
import datetime
from fpdf import FPDF

RESULTS_DIR = r"e:/EcoWatch-AI/results"


class ComplianceReport(FPDF):
    """Custom FPDF subclass with EcoWatch header/footer (Unicode-safe)."""

    def __init__(self, zone: str, analysis_type: str):
        super().__init__()
        self.zone          = zone
        self.analysis_type = analysis_type
        self.set_auto_page_break(auto=True, margin=20)

    def _safe(self, text: str) -> str:
        """Replace non-Latin-1 chars with ASCII equivalents."""
        replacements = {
            "\u2014": "-",   # em-dash  ->  hyphen
            "\u2013": "-",   # en-dash  ->  hyphen
            "\u2019": "'",   # right single quote
            "\u2018": "'",   # left single quote
            "\u201c": '"',   # left double quote
            "\u201d": '"',   # right double quote
            "\u00b2": "2",   # superscript 2  ->  2
            "\u2122": "(TM)",
            "\u00ae": "(R)",
        }
        for src, dst in replacements.items():
            text = text.replace(src, dst)
        return text.encode("latin-1", errors="ignore").decode("latin-1")

    def header(self):
        self.set_fill_color(15, 20, 26)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(78, 222, 163)
        self.set_xy(10, 4)
        self.cell(0, 10, self._safe("EcoWatch AI  |  Environmental Compliance Report"), ln=0)
        self.set_text_color(180, 180, 180)
        self.set_font("Helvetica", "", 8)
        self.set_xy(140, 6)
        self.cell(0, 6, self._safe(f"CONFIDENTIAL  |  {datetime.date.today().strftime('%d %b %Y')}"), ln=0)
        self.ln(14)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, self._safe(f"Page {self.page_no()} | Generated by EcoWatch AI Synthetic Observatory"), 0, 0, "C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(30, 37, 48)
        self.set_text_color(78, 222, 163)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 9, self._safe(f"  {title}"), ln=1, fill=True)
        self.ln(2)
        self.set_text_color(30, 30, 30)

    def kv_row(self, key: str, value: str, alternate: bool = False):
        if alternate:
            self.set_fill_color(240, 244, 248)
        else:
            self.set_fill_color(255, 255, 255)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(58, 7, self._safe(f"  {key}"), border=0, fill=True)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(20, 20, 20)
        self.cell(0, 7, self._safe(value), border=0, fill=True, ln=1)


def generate_report(
    zone_name:     str,
    analysis_type: str,
    violations:    int,
    confidence:    float,
    coverage_km2:  float,
    blobs:         list,
    heatmap_path:  str | None = None,
) -> str:
    """
    Build a PDF compliance report and save it to RESULTS_DIR.
    Returns the absolute path of the saved PDF.
    """
    os.makedirs(RESULTS_DIR, exist_ok=True)

    ts       = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Compliance_Report_{zone_name}_{ts}.pdf"
    out_path = os.path.join(RESULTS_DIR, filename)

    pdf = ComplianceReport(zone_name, analysis_type)
    pdf.add_page()
    pdf.section_title("Report Overview")

    alt = False
    for key, val in [
        ("Industrial Zone",   zone_name),
        ("Analysis Type",     analysis_type),
        ("Report Generated",  datetime.datetime.now().strftime("%d %b %Y, %H:%M:%S")),
        ("Violations Found",  str(violations)),
        ("Model Confidence",  f"{confidence:.1f}%"),
        ("Total Coverage",    f"{coverage_km2:.4f} km sq"),
        ("Status",            "ACTION REQUIRED" if violations > 0 else "COMPLIANT"),
    ]:
        pdf.kv_row(key, val, alt)
        alt = not alt
    if blobs:
        pdf.section_title(f"Detected Violations  ({len(blobs)} regions)")

        pdf.set_fill_color(22, 33, 48)
        pdf.set_text_color(78, 222, 163)
        pdf.set_font("Helvetica", "B", 9)
        for hdr, w in [("ID", 20), ("Severity", 28), ("Latitude", 40), ("Longitude", 40), ("Area km sq", 31), ("Priority", 31)]:
            pdf.cell(w, 8, hdr, border=1, fill=True, align="C")
        pdf.ln()

        sev_map = {"High": "CRITICAL", "Medium": "REVIEW", "Low": "MONITOR"}
        row_colors = {
            "High":   (255, 220, 220),
            "Medium": (255, 243, 210),
            "Low":    (220, 255, 235),
        }

        for b in blobs:
            sev = b.get("severity", "Low")
            rc  = row_colors.get(sev, (245, 245, 245))
            pdf.set_fill_color(*rc)
            pdf.set_text_color(40, 40, 40)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(20, 7, pdf._safe(b.get("id", "")),                         border=1, fill=True, align="C")
            pdf.cell(28, 7, pdf._safe(sev),                                      border=1, fill=True, align="C")
            pdf.cell(40, 7, pdf._safe(f"{b.get('lat', 0):.6f} N"),               border=1, fill=True, align="C")
            pdf.cell(40, 7, pdf._safe(f"{b.get('lon', 0):.6f} E"),               border=1, fill=True, align="C")
            pdf.cell(31, 7, pdf._safe(f"{b.get('area_km2', 0):.5f}"),            border=1, fill=True, align="C")
            pdf.cell(31, 7, pdf._safe(sev_map.get(sev, sev)),                    border=1, fill=True, align="C")
            pdf.ln()

    else:
        pdf.section_title("Violation Analysis")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 10, "  No significant violations detected. Zone is currently COMPLIANT.", ln=1)
    if heatmap_path and os.path.exists(heatmap_path):
        pdf.section_title("Visual Analysis - Heatmap Evidence")
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        if analysis_type == "Vegetation Segmentation":
            label = "Dark = no vegetation loss | Bright = vegetation loss detected"
        else:
            label = "Blue = no change | Red/Yellow = high-probability change detected"
        pdf.cell(0, 5, f"  {label}", ln=1)
        pdf.ln(2)
        pdf.image(heatmap_path, x=45, w=120)
        pdf.ln(4)
    pdf.section_title("Regulatory Recommendations")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)

    if violations > 0:
        recs = [
            "1. Issue formal notices to plotholders within flagged GPS coordinates.",
            "2. Schedule ground-truth field inspection within 7 working days.",
            "3. Cross-reference flagged coordinates against approved construction permits.",
            "4. If green belt encroachment confirmed, invoke KIADB enforcement provisions.",
            "5. Re-run EcoWatch AI analysis post-remediation to confirm compliance.",
        ]
    else:
        recs = [
            "1. Zone appears compliant. Continue monthly monitoring schedule.",
            "2. Archive this report as baseline for future change detection.",
            "3. No immediate action required.",
        ]

    for rec in recs:
        pdf.cell(0, 6, pdf._safe(f"  {rec}"), ln=1)
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 5, pdf._safe(
        "DISCLAIMER: This report is generated by the EcoWatch AI automated satellite analysis system. "
        "Results are indicative only and should be verified by a qualified environmental officer before "
        "any regulatory action is taken."
    ))

    pdf.output(out_path)
    print(f"[ReportGen] Saved: {out_path}")
    return out_path
